# Generated by Django 4.0.5 on 2022-07-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVfile_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='sku')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
            ],
        ),
    ]
